# Generated by Django 6.0.3 on 2026-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_channel_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
