# Generated by Django 6.0.3 on 2026-05-03 09:04

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('all', 'Tous les canaux')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agents', models.ManyToManyField(blank=True, limit_choices_to={'role': 'agent'}, related_name='agent_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_groups',
            },
        ),
    ]
