# Generated by Django 6.0.3 on 2026-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_default_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manual_status',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20, null=True),
        ),
    ]
